export const financials = {
  totalEarned: 47250,
  pendingInvoices: 12800,
  totalExpenses: 8340,
  annualGoal: 80000,
};

export const deals = [
  {
    id: 1,
    brand: "Petlibro",
    logo: "PL",
    logoColor: "#4F7FFA",
    domain: "petlibro.com",
    value: 4500,
    category: "automatic feeders",
    stage: "in production",
    paymentStatus: "invoiced",
    invoiceNumber: "INV-1043",
    deliverables: [
      { type: "Send content brief to brand", dueDate: "2026-04-01", done: false },
      { type: "Story Set (x3)", dueDate: "2026-04-02", done: false },
      { type: "Instagram Reel", dueDate: "2026-04-04", done: false },
      { type: "TikTok Video", dueDate: "2026-04-06", done: false },
    ],
    usageRightsExpiry: "2026-10-01",
    notes: "60-day exclusivity on automatic feeder category",
  },
  {
    id: 2,
    brand: "Litter Genie",
    logo: "LG",
    logoColor: "#8B5CF6",
    domain: "littergenie.com",
    value: 3200,
    category: "litter & waste",
    stage: "signed",
    paymentStatus: "unpaid",
    invoiceNumber: null,
    deliverables: [
      { type: "Submit draft script for approval", dueDate: "2026-04-03", done: false },
      { type: "YouTube Integration (60s)", dueDate: "2026-04-07", done: false },
      { type: "Instagram Carousel", dueDate: "2026-04-08", done: false },
    ],
    usageRightsExpiry: "2026-07-15",
    notes: "Brand approval required 5 days before posting",
  },
  {
    id: 3,
    brand: "Fresh Step",
    logo: "FS",
    logoColor: "#10B981",
    domain: "freshstep.com",
    value: 6000,
    category: "litter & waste",
    stage: "negotiating",
    paymentStatus: "unpaid",
    invoiceNumber: null,
    deliverables: [
      { type: "TikTok Series (x3)", dueDate: "2026-05-01", done: false },
      { type: "Instagram Reel", dueDate: "2026-05-05", done: false },
    ],
    usageRightsExpiry: "2026-12-31",
    notes: "Counter-offered $6k, waiting on response",
  },
  {
    id: 4,
    brand: "Dodo",
    logo: "DO",
    logoColor: "#F59E0B",
    domain: "shopdodo.com",
    value: 2800,
    category: "pet accessories",
    stage: "delivered",
    paymentStatus: "invoiced",
    invoiceNumber: "INV-1042",
    deliverables: [
      { type: "Instagram Reel", dueDate: "2026-03-28", done: true },
      { type: "TikTok Video", dueDate: "2026-03-28", done: true },
    ],
    usageRightsExpiry: "2026-09-28",
    notes: "All deliverables submitted. Invoice #1042 sent.",
  },
  {
    id: 5,
    brand: "PetSafe",
    logo: "PS",
    logoColor: "#EF4444",
    domain: "petsafe.net",
    value: 5500,
    category: "pet health",
    stage: "paid",
    paymentStatus: "paid",
    invoiceNumber: "INV-1038",
    deliverables: [
      { type: "YouTube Video", dueDate: "2026-03-01", done: true },
      { type: "Instagram Reel", dueDate: "2026-03-01", done: true },
    ],
    usageRightsExpiry: "2026-09-01",
    notes: "Payment received 2026-03-15",
  },
];

export const opportunities = [
  {
    id: 1,
    brand: "Meowtel",
    logo: "MT",
    logoColor: "#6366F1",
    domain: "meowtel.com",
    source: "Gmail",
    subject: "Partnership Opportunity — Meowtel x Your Channel",
    preview: "Hi! We love your content and think your audience would be a perfect fit for Meowtel, the #1 cat sitting marketplace. We'd love to explore a paid partnership...",
    date: "2026-04-01",
    estimatedValue: "2,000–4,000",
    category: "pet services",
    lastContacted: { name: "Jamie R. (Meowtel Partnerships)", date: "2026-04-01" },
    status: "new",
    snoozed: false,
    type: "proposal",
    gmailSimulated: true,
    actionNeeded: "Reply to partnership proposal",
  },
  {
    id: 2,
    brand: "Catit",
    logo: "CA",
    logoColor: "#EC4899",
    domain: "catit.com",
    source: "Instagram DM",
    subject: "Collab interest from Catit",
    preview: "Hey! We've been following your page for a while — your cats are adorable 😍 We'd love to send you our new Pixi fountain and discuss a paid collab...",
    date: "2026-03-31",
    estimatedValue: "1,500–3,000",
    category: "water fountains",
    lastContacted: { name: "catit_official", date: "2026-03-31" },
    status: "new",
    snoozed: false,
    type: "product_offer",
    actionNeeded: "Respond — they want to send product for review",
  },
  {
    id: 3,
    brand: "NomNomNow",
    logo: "NN",
    logoColor: "#F97316",
    domain: "nomnomfood.com",
    source: "TikTok DM",
    subject: "NomNomNow creator program",
    preview: "Hi creator! NomNomNow is launching a new creator program for Q2. We're offering flat-rate sponsorships for TikTok and Instagram. Would love to connect...",
    date: "2026-03-30",
    estimatedValue: "3,000–5,000",
    category: "pet food",
    lastContacted: { name: "@nomnomhq", date: "2026-03-30" },
    status: "new",
    snoozed: false,
    type: "proposal",
    actionNeeded: "Reply to creator program inquiry",
  },
  {
    id: 4,
    brand: "Arm & Hammer Pet",
    logo: "AH",
    logoColor: "#0EA5E9",
    domain: "armandhammer.com",
    source: "Gmail",
    subject: "Re: Creator collaboration — litter line",
    preview: "Following up on our previous email — we're looking to partner with cat creators for our new clumping litter launch. Budget is flexible for the right creator...",
    date: "2026-03-29",
    estimatedValue: "2,500–4,500",
    category: "litter & waste",
    lastContacted: { name: "Priya M. (Brand Partnerships)", date: "2026-03-29" },
    status: "new",
    snoozed: false,
    type: "proposal",
    gmailSimulated: true,
    actionNeeded: "Reply — they followed up, brand hasn't heard back",
  },
  {
    id: 5,
    brand: "Hepper",
    logo: "HP",
    logoColor: "#14B8A6",
    domain: "hepper.com",
    source: "Gmail",
    subject: "Hepper Pod Bed — sending you one to try!",
    preview: "Hey! We're sending you one of our new Pod Beds for your cats to try. No obligation to post — but if you love it, we'd love to chat about a deal. Tracking info attached...",
    date: "2026-03-28",
    estimatedValue: "1,000–2,500",
    category: "pet furniture",
    lastContacted: { name: "hello@hepper.com", date: "2026-03-28" },
    status: "new",
    snoozed: false,
    type: "product_sent",
    gmailSimulated: true,
    actionNeeded: "Product arriving soon — try it out and follow up",
  },
  {
    id: 6,
    brand: "Smalls",
    logo: "SM",
    logoColor: "#A855F7",
    domain: "smallsforsmalls.com",
    source: "Gmail",
    subject: "Fresh food for your cats — want to try Smalls?",
    preview: "Hi! Smalls makes human-grade fresh cat food and we'd love to get your cats on a free trial. We work with creators on a monthly basis and would love to discuss a long-term partnership...",
    date: "2026-03-26",
    estimatedValue: "4,000–8,000",
    category: "pet food",
    lastContacted: { name: "partnerships@smallsforsmalls.com", date: "2026-03-26" },
    status: "new",
    snoozed: false,
    type: "proposal",
    gmailSimulated: true,
    actionNeeded: "Haven't replied — last message was from them 6 days ago",
  },
];

export const pastDeals = [
  {
    id: 101,
    brand: "PetSafe",
    logo: "PS",
    logoColor: "#EF4444",
    domain: "petsafe.net",
    value: 5500,
    category: "pet health",
    paidDate: "2026-03-15",
    invoiceNumber: "INV-1038",
    paymentMethod: "wire",
    deliverables: [
      { type: "YouTube Video", dueDate: "2026-03-01", done: true },
      { type: "Instagram Reel", dueDate: "2026-03-01", done: true },
    ],
    usageRightsExpiry: "2026-09-01",
    notes: "Smooth deal. They paid within 10 days of invoice. Great brand to work with again.",
  },
  {
    id: 102,
    brand: "Tuft + Paw",
    logo: "TP",
    logoColor: "#F59E0B",
    domain: "tuftandpaw.com",
    value: 3800,
    category: "cat furniture",
    paidDate: "2026-02-20",
    invoiceNumber: "INV-1035",
    paymentMethod: "paypal",
    deliverables: [
      { type: "Instagram Reel", dueDate: "2026-02-10", done: true },
      { type: "TikTok Video", dueDate: "2026-02-10", done: true },
      { type: "Blog Post", dueDate: "2026-02-15", done: true },
    ],
    usageRightsExpiry: "2026-08-20",
    notes: "Required 3 rounds of revision on the reel. Budget for edit time next time.",
  },
  {
    id: 103,
    brand: "Chewy",
    logo: "CW",
    logoColor: "#3B82F6",
    domain: "chewy.com",
    value: 7200,
    category: "pet retail",
    paidDate: "2026-01-30",
    invoiceNumber: "INV-1031",
    paymentMethod: "wire",
    deliverables: [
      { type: "YouTube Video (dedicated)", dueDate: "2026-01-20", done: true },
      { type: "Instagram Reel x2", dueDate: "2026-01-22", done: true },
      { type: "TikTok x2", dueDate: "2026-01-22", done: true },
    ],
    usageRightsExpiry: "2027-01-30",
    notes: "Best rate so far. They renewed for Q2 — flag for re-sign in March.",
  },
  {
    id: 104,
    brand: "Whisker",
    logo: "WH",
    logoColor: "#8B5CF6",
    domain: "whisker.com",
    value: 6500,
    category: "automatic litter",
    paidDate: "2025-12-18",
    invoiceNumber: "INV-1028",
    paymentMethod: "stripe",
    deliverables: [
      { type: "YouTube Integration (90s)", dueDate: "2025-12-08", done: true },
      { type: "TikTok Series (x3)", dueDate: "2025-12-10", done: true },
    ],
    usageRightsExpiry: "2026-06-18",
    notes: "Exclusivity expired June 2026. Open to competitors in automatic litter after that.",
  },
];

export const targets = [
  {
    id: 201,
    brand: "Chewy",
    logo: "CW",
    logoColor: "#3B82F6",
    domain: "chewy.com",
    category: "pet retail",
    website: "chewy.com",
    estimatedValue: "6,000–10,000",
    priority: "high",
    status: "in talks",
    notes: "Had a great Q1 deal. Reach out in early April about Q2 renewal — they mentioned being interested.",
    addedDate: "2026-01-15",
    contactName: "Sarah K.",
    contactEmail: "sarah.k@chewy.com",
  },
  {
    id: 202,
    brand: "Blue Buffalo",
    logo: "BB",
    logoColor: "#2563EB",
    domain: "bluebuffalo.com",
    category: "pet food",
    website: "bluebuffalo.com",
    estimatedValue: "5,000–9,000",
    priority: "high",
    status: "not contacted",
    notes: "Big budget brand. Find the creator partnerships contact — probably through their agency.",
    addedDate: "2026-02-01",
    contactName: null,
    contactEmail: null,
  },
  {
    id: 203,
    brand: "Friskies",
    logo: "FR",
    logoColor: "#EF4444",
    domain: "friskies.com",
    category: "pet food",
    website: "friskies.com",
    estimatedValue: "4,000–7,000",
    priority: "medium",
    status: "not contacted",
    notes: "Purina-owned. Would need to go through their influencer agency. Research who handles this.",
    addedDate: "2026-02-10",
    contactName: null,
    contactEmail: null,
  },
  {
    id: 204,
    brand: "Bissell Pet",
    logo: "BP",
    logoColor: "#10B981",
    domain: "bissell.com",
    category: "pet cleaning",
    website: "bissell.com",
    estimatedValue: "3,000–5,000",
    priority: "medium",
    status: "contacted",
    notes: "Sent cold pitch via email 2026-03-01. No reply yet. Follow up after 2 weeks.",
    addedDate: "2026-02-28",
    contactName: "partnerships@bissell.com",
    contactEmail: "partnerships@bissell.com",
  },
  {
    id: 205,
    brand: "Fancy Feast",
    logo: "FF",
    logoColor: "#F59E0B",
    domain: "fancyfeast.com",
    category: "pet food",
    website: "fancyfeast.com",
    estimatedValue: "5,000–8,000",
    priority: "high",
    status: "not contacted",
    notes: "Premium brand that aligns perfectly with audience. Find their creator contact — likely through Nestlé Purina's influencer team.",
    addedDate: "2026-03-05",
    contactName: null,
    contactEmail: null,
  },
  {
    id: 206,
    brand: "Yeowww!",
    logo: "YW",
    logoColor: "#A855F7",
    domain: "yeowww.com",
    category: "cat toys",
    website: "yeowww.com",
    estimatedValue: "1,500–3,000",
    priority: "low",
    status: "not contacted",
    notes: "Cult brand. Smaller budget but high engagement likely. Good for an authentic post.",
    addedDate: "2026-03-20",
    contactName: null,
    contactEmail: null,
  },
];
