export const threads = [
  {
    id: 1,
    brand: "Fresh Step",
    logo: "FS",
    logoColor: "#7C5CFC",
    domain: "freshstep.com",
    contact: { name: "Sarah Chen", email: "sarah.chen@freshstep.com" },
    firstReached: "2026-01-10",
    lastMessage: "2026-02-20",
    offer: "Sponsored TikTok + Instagram Reel",
    product: "Fresh Step Clean Paws Litter",
    theirRate: 1500,
    yourRate: 2500,
    status: "deal_closed",
    revenue: 2500,
    category: "litter & cat care",
  },
  {
    id: 2,
    brand: "Petlibro",
    logo: "PL",
    logoColor: "#F59E0B",
    domain: "petlibro.com",
    contact: { name: "James Park", email: "james@petlibro.com" },
    firstReached: "2026-02-15",
    lastMessage: "2026-02-28",
    offer: "2x Instagram Reels + product seeding",
    product: "Granary Feeder Pro",
    theirRate: 800,
    yourRate: 1800,
    status: "reply_needed",
    revenue: null,
    category: "pet tech",
  },
  {
    id: 3,
    brand: "Litter Genie",
    logo: "LG",
    logoColor: "#10B981",
    domain: "littergenieplus.com",
    contact: { name: "Mia Torres", email: "mia.torres@littergenie.com" },
    firstReached: "2026-03-01",
    lastMessage: "2026-03-28",
    offer: "Sponsored video series — 3 TikToks",
    product: "Litter Genie Plus Disposal System",
    theirRate: 2000,
    yourRate: 3500,
    status: "deal_closed",
    revenue: 3500,
    category: "litter & cat care",
  },
  {
    id: 4,
    brand: "The Dodo",
    logo: "TD",
    logoColor: "#3B82F6",
    domain: "thedodo.com",
    contact: { name: "Alex Rivera", email: "alex.r@thedodo.com" },
    firstReached: "2026-03-10",
    lastMessage: "2026-04-01",
    offer: "Content licensing + feature",
    product: null,
    theirRate: 500,
    yourRate: 1200,
    status: "you_replied",
    revenue: null,
    category: "media",
  },
  {
    id: 5,
    brand: "NomNomNow",
    logo: "NN",
    logoColor: "#EF4444",
    domain: "nomnomnow.com",
    contact: { name: "Priya Patel", email: "priya@nomnomnow.com" },
    firstReached: "2026-01-20",
    lastMessage: "2026-02-15",
    offer: "Monthly ambassador deal",
    product: "Fresh Cat Food Subscription",
    theirRate: 1500,
    yourRate: 1800,
    status: "deal_closed",
    revenue: 1800,
    category: "pet food",
  },
  {
    id: 6,
    brand: "Chewy",
    logo: "CW",
    logoColor: "#EC4899",
    domain: "chewy.com",
    contact: { name: "Marcus Lee", email: "marcus.lee@chewy.com" },
    firstReached: "2026-03-25",
    lastMessage: "2026-04-02",
    offer: "Product seeding + affiliate program",
    product: "Chewy Affiliate + Free Product Haul",
    theirRate: "product",
    yourRate: 1000,
    status: "reply_needed",
    revenue: null,
    category: "pet retail",
  },
  {
    id: 7,
    brand: "Furbo",
    logo: "FB",
    logoColor: "#8B5CF6",
    domain: "furbo.com",
    contact: { name: "Lisa Wang", email: "lisa.wang@furbo.com" },
    firstReached: "2026-02-01",
    lastMessage: "2026-03-12",
    offer: "Paid Instagram post + Story set",
    product: "Furbo 360° Dog Camera",
    theirRate: 600,
    yourRate: 1500,
    status: "waiting_on_them",
    revenue: null,
    category: "pet tech",
  },
  {
    id: 8,
    brand: "PetSafe",
    logo: "PS",
    logoColor: "#0EA5E9",
    domain: "petsafe.net",
    contact: { name: "Tom Bradley", email: "tom.bradley@petsafe.net" },
    firstReached: "2026-03-18",
    lastMessage: "2026-04-03",
    offer: "2x TikTok videos — product demo",
    product: "Smart Feed Automatic Feeder",
    theirRate: 1200,
    yourRate: 2000,
    status: "you_replied",
    revenue: null,
    category: "pet safety",
  },
  {
    id: 9,
    brand: "BarkBox",
    logo: "BB",
    logoColor: "#F97316",
    domain: "barkbox.com",
    contact: { name: "Emma Nguyen", email: "emma@barkbox.com" },
    firstReached: "2026-04-01",
    lastMessage: "2026-04-04",
    offer: "Unboxing video + honest review",
    product: "BarkBox Monthly Subscription",
    theirRate: 400,
    yourRate: 900,
    status: "reply_needed",
    revenue: null,
    category: "pet subscription",
  },
  {
    id: 10,
    brand: "Wellness Pet",
    logo: "WP",
    logoColor: "#14B8A6",
    domain: "wellnesspet.com",
    contact: { name: "David Kim", email: "david.kim@wellnesspet.com" },
    firstReached: "2025-12-10",
    lastMessage: "2026-01-25",
    offer: "3-month sponsored series",
    product: "CORE Grain-Free Dry Cat Food",
    theirRate: 3000,
    yourRate: 4500,
    status: "deal_closed",
    revenue: 4500,
    category: "pet food",
  },
];

export const analyticsData = {
  thisYear: {
    year: 2026,
    monthly: [2, 2, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    totalBrands: 9,
    dealsClosedCount: 3,
    revenue: 8800,
    closeRate: 33,
  },
  lastYear: {
    year: 2025,
    monthly: [1, 1, 2, 2, 2, 1, 2, 2, 3, 2, 1, 2],
    totalBrands: 21,
    dealsClosedCount: 5,
    revenue: 19400,
    closeRate: 24,
  },
  funnel: [
    { label: "Reached out", count: 9 },
    { label: "Got response", count: 7 },
    { label: "Negotiating", count: 5 },
    { label: "Closed", count: 3 },
  ],
  categories: [
    { label: "Litter & cat care", count: 2 },
    { label: "Pet tech", count: 2 },
    { label: "Pet food", count: 2 },
    { label: "Pet retail", count: 1 },
    { label: "Pet safety", count: 1 },
    { label: "Media", count: 1 },
    { label: "Pet subscription", count: 1 },
  ],
};
